{{- if or (.Values.serviceAccount.create) (and (.Values.serviceAccount.name) (ne .Values.serviceAccount.name "")) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "fullstack-app.fullname" .) .Values.serviceAccount.name }}
{{- end }}
