apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack-app.frontend.fullname" . }}
  labels:
    {{- include "fullstack-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: {{ include "fullstack-app.frontend.fullname" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack-app.backend.fullname" . }}
  labels:
    {{- include "fullstack-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    app: {{ include "fullstack-app.backend.fullname" . }}
